# Data Preprocessing Tools

## Importing the libraries

In [301]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [302]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [303]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 44.0 72000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [304]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [305]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [306]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 44.0 72000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 67000.0]
 ['France' 35.0 58000.0]
 ['Spain' 40.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [307]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [308]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 67000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 40.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [309]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [310]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [311]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [312]:
print(X_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 40.0 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [313]:
print(X_test)

[[0.0 1.0 0.0 40.0 67000.0]
 [0.0 0.0 1.0 44.0 72000.0]]


In [314]:
print(y_train)

[1 0 1 0 0 0 1 0]


In [315]:
print(y_test)

[1 1]


## Feature Scaling

In [316]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [317]:
print(X_train)

[[1.0 0.0 0.0 -0.8333595796391723 -0.7213204519277457]
 [1.0 0.0 0.0 0.5952568425994088 0.5817100418772143]
 [1.0 0.0 0.0 1.230197474705445 1.2332252887796944]
 [0.0 1.0 0.0 -1.6270353697717175 -1.093614878729163]
 [0.0 0.0 1.0 -0.3571541055596453 -0.4420996318266829]
 [0.0 0.0 1.0 -0.03968378950662725 -1.2797620921298716]
 [1.0 0.0 0.0 -0.5158892635861543 0.11634200837544287]
 [0.0 1.0 0.0 1.5476677907584628 1.6055197155811116]]


In [318]:
print(X_test)

[[0.0 1.0 0.0 -0.03968378950662725 0.11634200837544287]
 [0.0 0.0 1.0 0.5952568425994088 0.5817100418772143]]
